In [7]:
import torch


val = torch.tensor([[1,1,4],[5,7,8]]).float()

print(f'val.mean(0,True)={val.mean(0,True)}')
print(val / val.mean(0,True))
print(f'val.mean(1,True)={val.mean(1,True)}')

val.mean(0,True)=tensor([[3., 4., 6.]])
tensor([[0.3333, 0.2500, 0.6667],
        [1.6667, 1.7500, 1.3333]])
val.mean(1,True)=tensor([[2.0000],
        [6.6667]])


In [13]:
import torch

val_1 = torch.tensor([[0, 1, 4], [5, 7, 8], [4, 6, 2]]).float()
val_2 = torch.tensor([[1, 1, 4, 1], [5, 7, 8, 1], [4, 6, 2, 1]]).float()
val_4 = torch.tensor([[1, 1, 4], [5, 7, 8], [4, 6, 2]]).float()
val_3 = torch.cat([val_1, val_2], -1)
print(val_3)
print(f"val_1.mean()={val_1.mean()}")
print(f"val_1.log()={val_1.log().clamp_min(1e-8)}")
print(torch.cat((val_1, val_4)))
print(f"val_4.sum(1, True)={val_4.sum(1, True)}")
print(f"val_4/val_4.sum(1, True)={val_4/val_4.sum(1, True)}")
print(val_3.sum(1, True))

tensor([[0., 1., 4., 1., 1., 4., 1.],
        [5., 7., 8., 5., 7., 8., 1.],
        [4., 6., 2., 4., 6., 2., 1.]])
val_1.mean()=4.111111164093018
val_1.log()=tensor([[1.0000e-08, 1.0000e-08, 1.3863e+00],
        [1.6094e+00, 1.9459e+00, 2.0794e+00],
        [1.3863e+00, 1.7918e+00, 6.9315e-01]])
tensor([[0., 1., 4.],
        [5., 7., 8.],
        [4., 6., 2.],
        [1., 1., 4.],
        [5., 7., 8.],
        [4., 6., 2.]])
val_4.sum(1, True)=tensor([[ 6.],
        [20.],
        [12.]])
val_4/val_4.sum(1, True)=tensor([[0.1667, 0.1667, 0.6667],
        [0.2500, 0.3500, 0.4000],
        [0.3333, 0.5000, 0.1667]])
tensor([[12.],
        [41.],
        [25.]])


In [37]:
import torch

input = torch.tensor(
    [[1, 1, 0, 1], [3, 1, 1, 2], [2, 2, 3, 3], [3, 0, 0, 0], [5, 0, 0, 5]]
).float()
reshaped = input.view(-1, input.size()[-1])
l_sorted, l_indices = reshaped.sort(-1, descending=True)
l_cumsum = l_sorted.cumsum(-1)
l_rhos = torch.arange(1, l_sorted.size(-1) + 1).float().unsqueeze(0)
l_support = (l_sorted * l_rhos) > (l_cumsum - 1)
l_k = l_support.sum(-1).unsqueeze(-1)
l_tau_sum = l_cumsum.gather(-1, l_k - 1)
l_tau = (l_tau_sum - 1) / l_k.float()
output = torch.clamp_min(reshaped - l_tau, min=0.0)
output = output.view_as(input)

In [13]:
import torch

parent_idx = torch.tensor([-1, 0, 0, 1, 1, 2, 2])
child_idx = (parent_idx >= 0).nonzero().squeeze(1)
print(f"child_idx={child_idx}")
parent_indices = parent_idx.index_select(0, child_idx)
print(f"parent_indices={parent_indices}")
l_degree_map = torch.zeros(parent_idx.size(0), dtype=torch.long)
ones = torch.ones(child_idx.size(0), dtype=torch.long)
l_degree_map.scatter_add_(0, parent_indices, ones)
print(f"l_degree_map={l_degree_map}")
l_degree_map = l_degree_map.clamp_min(1).unsqueeze(1)
print(f"l_degree_map={l_degree_map}")


child_idx=tensor([1, 2, 3, 4, 5, 6])
parent_indices=tensor([0, 0, 1, 1, 2, 2])
l_degree_map=tensor([2, 2, 2, 0, 0, 0, 0])
l_degree_map=tensor([[2],
        [2],
        [2],
        [1],
        [1],
        [1],
        [1]])
