In [7]:
import torch


val = torch.tensor([[1,1,4],[5,7,8]]).float()

print(f'val.mean(0,True)={val.mean(0,True)}')
print(val / val.mean(0,True))
print(f'val.mean(1,True)={val.mean(1,True)}')

val.mean(0,True)=tensor([[3., 4., 6.]])
tensor([[0.3333, 0.2500, 0.6667],
        [1.6667, 1.7500, 1.3333]])
val.mean(1,True)=tensor([[2.0000],
        [6.6667]])


In [1]:
import torch

val_1 = torch.tensor([[1, 1, 4], [5, 7, 8], [4, 6, 2]]).float()
val_2 = torch.tensor([[1, 1, 4, 1], [5, 7, 8, 1], [4, 6, 2, 1]]).float()
val_4 = torch.tensor([[1, 1, 4], [5, 7, 8], [4, 6, 2]]).float()
val_3 = torch.cat([val_1, val_2], -1)
print(val_3)
print(torch.cat((val_1, val_4)))

tensor([[1., 1., 4., 1., 1., 4., 1.],
        [5., 7., 8., 5., 7., 8., 1.],
        [4., 6., 2., 4., 6., 2., 1.]])
tensor([[1., 1., 4.],
        [5., 7., 8.],
        [4., 6., 2.],
        [1., 1., 4.],
        [5., 7., 8.],
        [4., 6., 2.]])


In [7]:
import torch
v1 = torch.tensor([1, 1, 2, 3, 3, 3, 2, 2])
print(torch.unique_consecutive(v1,return_counts=True))
print(torch.unique(v1))



(tensor([1, 2, 3, 2]), tensor([2, 1, 3, 2]))
tensor([1, 2, 3])


In [13]:
import torch

parent_idx = torch.tensor([-1, 0, 0, 1, 1, 2, 2])
child_idx = (parent_idx >= 0).nonzero().squeeze(1)
print(f"child_idx={child_idx}")
parent_indices = parent_idx.index_select(0, child_idx)
print(f"parent_indices={parent_indices}")
l_degree_map = torch.zeros(parent_idx.size(0), dtype=torch.long)
ones = torch.ones(child_idx.size(0), dtype=torch.long)
l_degree_map.scatter_add_(0, parent_indices, ones)
print(f"l_degree_map={l_degree_map}")
l_degree_map = l_degree_map.clamp_min(1).unsqueeze(1)
print(f"l_degree_map={l_degree_map}")


child_idx=tensor([1, 2, 3, 4, 5, 6])
parent_indices=tensor([0, 0, 1, 1, 2, 2])
l_degree_map=tensor([2, 2, 2, 0, 0, 0, 0])
l_degree_map=tensor([[2],
        [2],
        [2],
        [1],
        [1],
        [1],
        [1]])
